### ISSUE TITLE
预加载的情况，子组件页面刷新时，不能确保地图的初始化在api加载完成以后

### ISSUE THREAD

**Issue by limeng1900** [iDerekLi/amap-js#11]
子组件中使用` const { AMap, AMapUI } = AMapJS.store.getAll()`加载AMap，当子组件页面强制刷新时，main.js重新加载amap api，子组件中如何控制在api加载完成后再初始化地图对象？

**Comment by iDerekLi** [comment]
目前store只是负责暂存AMap 和 AMapUI的内存地址, 因为AMap和AMapUI的特点只能注册在window顶级对象中. 子组件刷新只要能确保加载顺序就可以. 通常可以采用`v-if`或编写`ready`等类型的初始化方法.

**Comment by limeng1900** [comment]
好的，感谢回复
