### ISSUE TITLE
how to load amap loca library

### ISSUE THREAD

**Issue by tenstep** [iDerekLi/amap-js#19]
there's loca-loader.js in lib directory, but how to use it? When i use it the same like AMapLoader, errors would appear as follow:
> TypeError: amap_js__WEBPACK_IMPORTED_MODULE_10__.default.LocaLoader is not a constructor

**Comment by iDerekLi** [comment]
`LocaLoader` will be released in the next version.
Currently it can be used directly by reference:
```
import LocaLoader from "amap-js/lib/loaders/loca-loader";
```

**Comment by iDerekLi** [comment]
🥳The new version has been released! ! !
Update and install v2.0.3 and higher (including v2.0.3) to use [LocaLoader](https://iderekli.github.io/amap-js/guide/loca-loader.html).
