### ISSUE TITLE
vue项目中引用报错无法调用loadui方法

### ISSUE THREAD

**Issue by Iamliuyufeng** [iDerekLi/amap-js#30]
![image](https://user-images.githubusercontent.com/23160197/101583369-52eeb800-3a16-11eb-9743-6f20f06460df.png)
报错：
![image](https://user-images.githubusercontent.com/23160197/101583396-60a43d80-3a16-11eb-94f3-b3e6c486c565.png)

**Comment by yueyongxidain** [comment]
返回的不可迭代

**Comment by iDerekLi** [comment]
正在尽力排查, 您可以使用 https://codepen.io/ 来上传测试代码帮助排查
