### ISSUE TITLE
大佬 能不能整一个 地图搜索的功能 

### ISSUE THREAD

**Issue by TomYule** [iDerekLi/amap-js#38]
大佬 能不能整一个 地图搜索的功能 
https://jimnox.gitee.io/amap-vue/examples/coord-picker.html
类似酱紫

**Comment by TomYule** [comment]
像一些用了您的组件的案例 大佬 可否加上 
列如
https://blog.csdn.net/qq_51553982/article/details/123014795

**Comment by iDerekLi** [comment]
很抱歉！这个项目最初是由于高德没有提供ES Module模式加载而诞生的项目，由于不同开发者会使用不同地图地图版本
，而且对于加载器来说它通常也不涉及地图本身功能逻辑制作。
建议：如果您需要仅使用地图某一功能而不是加载地图API本身，建议在您项目中开发相对较为合适的。

**Comment by TomYule** [comment]
大佬 你可以的
